### ISSUE TITLE
Handling useful variants that don't work on their own

### ISSUE THREAD

**Issue by thirdpolice** [ldeluigi/commander-spellbook-backend#13]
As discussed on Discord with the Ad Nauseam + Transcendence example, some niche variants don't really work on their own, but could still be useful to keep for auto-generation purposes. The "OK" status and "Not working" statuses both have downsides for these combos, so we need to decide how to handle these.

**Comment by ldeluigi** [comment]
From discord

> Trying to think how to implement that with the current system. Tagging cards doesn't really help, because a card might have some instant-speed features (activated abilities) and some sorcery-speed.
Deloo — Today at 16:59
maybe adding a "Then you lose the game" effect?
then the frontend could filter for variants that don't have that effect unless they have "Win" too
DarthJeeling (they) — Today at 17:05
Hm, yeah, that could work. I was thinking it would be nice to find a more general solution, but maybe there aren't many niche situations other than 'losing the game' that can't be solved by writing in some prerequisites.
Deloo — Today at 17:06
we are talking about the same variants that "are useful but don't work on their own" right? 
DarthJeeling (they) — Today at 17:06
yes
