### ISSUE TITLE
Possible loop detected

### ISSUE THREAD

**Issue by bmp2** [ldeluigi/commander-spellbook-backend#45]
![image](https://user-images.githubusercontent.com/8248830/194409139-266f44e6-ce16-44f3-a92a-8e2c7dcd0624.png)
![image](https://user-images.githubusercontent.com/8248830/194409155-afc1d8d5-35f5-43ab-b18e-3ff1d7f3080b.png)

**Comment by bmp2** [comment]
![image](https://user-images.githubusercontent.com/8248830/194409672-cb0bf17e-3dc8-47c6-8899-b33cc9bebed5.png)
![image](https://user-images.githubusercontent.com/8248830/194409697-b3b14326-1f41-4e89-84ae-78e94ae5a1a0.png)

**Comment by ldeluigi** [comment]
It means one of:
1. You are hitting the recursion limit of 20 (a chain of 10 combos and 10 features)
2. A chain of combo and features requires itself

**Comment by bmp2** [comment]
It's an associativity problem then. In Magic there can be combos like this:
card(C) + card(A) = inf(F)
card(R) + card(D) = inf(E)

card(S) + inf(F) = inf(E)
inf(E) + card(Q) = inf(F)

Any of which is a useful combo in its own right. So yes, you should disallow the variant that uses just the last two combos. But you should allow both of the combos to exist.

**Comment by ldeluigi** [comment]
I could allow loops but the downside would be the impossibility to order card names in variant based on their "replaceability", which is a feature. Maybe we should talk about this with editors
